Repository SOEN-390-W2025/SOEN-390, pull requests merged in 2025-02, with the labels that each got.

#79 Feature/build workflow
  .github/actions/create-env/action.yaml
  .github/actions/setup-android-build/action.yaml
  .github/actions/setup-flutter/action.yaml
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .gitignore
  README.md
  concordia_nav/android/app/build.gradle
  concordia_nav/android/app/src/main/AndroidManifest.xml
  concordia_nav/android/settings.gradle
  concordia_nav/pubspec.yaml
Labels: performance-bug, devops, feature

#81 Feature/near by facility
  concordia_nav/lib/ui/campus_map/campus_map_view.dart
  concordia_nav/lib/ui/home/homepage_view.dart
  concordia_nav/lib/ui/indoor_map/indoor_map_view.dart
  concordia_nav/lib/ui/poi/poi_choice_view.dart
  concordia_nav/lib/ui/poi/poi_map_view.dart
  concordia_nav/lib/ui/setting/settings_page.dart
  concordia_nav/lib/widgets/custom_appbar.dart
  concordia_nav/lib/widgets/map_layout.dart
  concordia_nav/lib/widgets/poi_box.dart
  concordia_nav/pubspec.lock
  concordia_nav/test/homepage_test.dart
  concordia_nav/test/indoor_map_test.dart
  concordia_nav/test/poi_mapview_test.dart
  concordia_nav/test/poipage_test.dart
  concordia_nav/test/settingspage_test.dart
Labels: feature

#82 Feature/indoor outdoor
  concordia_nav/lib/ui/home/homepage_view.dart
  concordia_nav/lib/ui/indoor_location/indoor_location_view.dart
  concordia_nav/lib/ui/outdoor_location/outdoor_location_map_view.dart
  concordia_nav/lib/ui/poi/poi_choice_view.dart
  concordia_nav/lib/widgets/map_layout.dart
  concordia_nav/lib/widgets/search_bar.dart
  concordia_nav/test/homepage_test.dart
  concordia_nav/test/indoor_location_test.dart
  concordia_nav/test/outdoor_directions_test.dart
Labels: feature

#169 Feature/splash screen
  concordia_nav/android/app/src/main/res/drawable-v21/empty_drawable.xml
  concordia_nav/android/app/src/main/res/drawable-v21/launch_background.xml
  concordia_nav/android/app/src/main/res/drawable/empty_drawable.xml
  concordia_nav/android/app/src/main/res/drawable/launch_background.xml
  concordia_nav/android/app/src/main/res/values/colors.xml
  concordia_nav/android/app/src/main/res/values/styles.xml
  concordia_nav/assets/images/splash_screen.png
  concordia_nav/ios/Runner/Base.lproj/LaunchScreen.storyboard
  concordia_nav/lib/main.dart
  concordia_nav/lib/widgets/custom_appbar.dart
  concordia_nav/lib/widgets/splash_screen.dart
  concordia_nav/test/splash_screen_test.dart
Labels: feature

#168 Feature/calendar
  concordia_nav/lib/ui/setting/calendar/calendar_link_view.dart
  concordia_nav/lib/ui/setting/calendar/calendar_view.dart
  concordia_nav/lib/ui/setting/settings_page.dart
  concordia_nav/test/calendar_link_test.dart
  concordia_nav/test/calendar_link_view_test.dart
  concordia_nav/test/calendar_page_test.dart
  concordia_nav/test/calendar_view_test.dart
  concordia_nav/test/calendar_view_test.mocks.dart
  concordia_nav/test/settingspage_test.dart
Labels: feature

#167 test: add missing branch coverage across unit tests
  concordia_nav/test/accessibility_page_test.dart
  concordia_nav/test/campus_test.dart
  concordia_nav/test/indoor_location_test.dart
  concordia_nav/test/indoor_map_test.dart
  concordia_nav/test/outdoor_directions_test.dart
  concordia_nav/test/poipage_test.dart
Labels: test

#165 test: integration tests for Release 1
  concordia_nav/maestro/1_1_View_Map_Of_SGW.yaml
  concordia_nav/maestro/1_2_View_Map_Of_Loyola.yaml
  concordia_nav/maestro/1_3_Outdoor_Direction_Option.yaml
  concordia_nav/maestro/1_4_Upcoming_Class_Directions_Option.yaml
  concordia_nav/maestro/1_5_Indoor_Directions_Option.yaml
  concordia_nav/maestro/1_6_Indoor_Points_Of_Interest_Option.yaml
  concordia_nav/maestro/1_7_Accessibility_Settings.yaml
  concordia_nav/maestro/1_8_Guest_Settings.yaml
  concordia_nav/maestro/1_9_User_Settings.yaml
Labels: test

#196 feat: replace hardcoded POIs
  concordia_nav/assets/config/facility_options.json
  concordia_nav/lib/data/domain-model/poi.dart
  concordia_nav/lib/data/repositories/poi_repository.dart
  concordia_nav/lib/main.dart
  concordia_nav/lib/ui/home/homepage_view.dart
  concordia_nav/lib/ui/poi/poi_choice_view.dart
  concordia_nav/lib/ui/setting/calendar/calendar_link_view.dart
  concordia_nav/lib/ui/setting/settings_page.dart
  concordia_nav/lib/utils/poi/poi_viewmodel.dart
  concordia_nav/lib/widgets/custom_appbar.dart
  concordia_nav/lib/widgets/search_bar.dart
  concordia_nav/lib/widgets/splash_screen.dart
  concordia_nav/pubspec.lock
  concordia_nav/pubspec.yaml
  concordia_nav/test/calendar/calendar_link_test.dart
  concordia_nav/test/calendar/calendar_link_view_test.dart
  concordia_nav/test/calendar/calendar_page_test.dart
  concordia_nav/test/calendar/calendar_repository_test.dart
  concordia_nav/test/calendar/calendar_repository_test.mocks.dart
  concordia_nav/test/calendar/calendar_view_test.dart
  concordia_nav/test/calendar/calendar_view_test.mocks.dart
  concordia_nav/test/custom_appbar_test.dart
  concordia_nav/test/homepage_test.dart
  concordia_nav/test/map/campus_test.dart
  concordia_nav/test/map/indoor_location_test.dart
  concordia_nav/test/map/indoor_map_test.dart
  concordia_nav/test/map/map_service_test.dart
  concordia_nav/test/map/map_service_test.mocks.dart
  concordia_nav/test/map/map_viewmodel_test.dart
  concordia_nav/test/map/map_viewmodel_test.mocks.dart
  concordia_nav/test/map/outdoor_directions_test.dart
  concordia_nav/test/poi/poi_mapview_test.dart
  concordia_nav/test/poi/poi_mapview_test.mocks.dart
  concordia_nav/test/poi/poi_repository_test.dart
  concordia_nav/test/poi/poipage_test.dart
  concordia_nav/test/poi_mapview_test.dart
  concordia_nav/test/poipage_test.dart
  concordia_nav/test/settings/accessibility_page_test.dart
  concordia_nav/test/settings/settingspage_test.dart
  concordia_nav/test/splash_screen_test.dart
Labels: feature

#200 Feature/current location
  concordia_nav/android/app/src/main/AndroidManifest.xml
  concordia_nav/lib/data/services/indoor_routing_service.dart
  concordia_nav/lib/data/services/map_service.dart
  concordia_nav/lib/ui/campus_map/campus_map_view.dart
  concordia_nav/lib/ui/outdoor_location/outdoor_location_map_view.dart
  concordia_nav/lib/utils/map_viewmodel.dart
  concordia_nav/lib/widgets/map_control_buttons.dart
  concordia_nav/lib/widgets/map_layout.dart
  concordia_nav/lib/widgets/zoom_buttons.dart
  concordia_nav/pubspec.lock
  concordia_nav/test/indoor_map/indoor_routing_service_test.dart
  concordia_nav/test/map/campus_test.dart
  concordia_nav/test/map/map_service_test.dart
  concordia_nav/test/map/map_viewmodel_test.dart
  concordia_nav/test/map/map_viewmodel_test.mocks.dart
  concordia_nav/test/map/outdoor_directions_test.dart
Labels: feature

#205 [Refactor] Introduce New Conditional Expressions and Extract Navigation Logic for Dynamic Home Page
  concordia_nav/lib/data/services/map_service.dart
  concordia_nav/lib/main.dart
  concordia_nav/lib/ui/campus_map/campus_map_view.dart
  concordia_nav/lib/utils/map_viewmodel.dart
  concordia_nav/lib/utils/splash_screen_viewmodel.dart
  concordia_nav/lib/widgets/custom_appbar.dart
  concordia_nav/lib/widgets/splash_screen.dart
  concordia_nav/pubspec.lock
  concordia_nav/test/custom_appbar_test.dart
  concordia_nav/test/homepage_test.dart
  concordia_nav/test/map/campus_test.dart
  concordia_nav/test/map/campus_test.mocks.dart
  concordia_nav/test/map/map_service_test.mocks.dart
  concordia_nav/test/map/map_viewmodel_test.dart
  concordia_nav/test/map/map_viewmodel_test.mocks.dart
  concordia_nav/test/map/outdoor_directions_test.dart
  concordia_nav/test/map/outdoor_directions_test.mocks.dart
  concordia_nav/test/settings/accessibility_page_test.dart
  concordia_nav/test/splash_screen_test.dart
Labels: refactor

#207 Feature/building drawer
  concordia_nav/assets/maps/outdoor/all/polygons.json
  concordia_nav/lib/data/repositories/building_repository.dart
  concordia_nav/lib/data/services/building_service.dart
  concordia_nav/lib/data/services/map_service.dart
  concordia_nav/lib/ui/campus_map/campus_map_view.dart
  concordia_nav/lib/ui/outdoor_location/outdoor_location_map_view.dart
  concordia_nav/lib/utils/building_drawer_viewmodel.dart
  concordia_nav/lib/utils/map_viewmodel.dart
  concordia_nav/lib/widgets/building_info_drawer.dart
  concordia_nav/lib/widgets/map_control_buttons.dart
  concordia_nav/lib/widgets/map_layout.dart
  concordia_nav/pubspec.yaml
  concordia_nav/test/building/building_info_drawer_test.dart
  concordia_nav/test/building/building_repository_test.dart
  concordia_nav/test/building/building_service_test.dart
  concordia_nav/test/homepage_test.dart
  concordia_nav/test/map/campus_test.dart
  concordia_nav/test/map/campus_test.mocks.dart
  concordia_nav/test/map/map_service_test.dart
  concordia_nav/test/map/map_service_test.mocks.dart
  concordia_nav/test/map/map_viewmodel_test.dart
  concordia_nav/test/map/map_viewmodel_test.mocks.dart
  concordia_nav/test/map/outdoor_directions_test.dart
Labels: feature

#210 Feature/zoom directions
  concordia_nav/lib/data/services/map_service.dart
  concordia_nav/lib/utils/map_viewmodel.dart
  concordia_nav/test/map/map_service_test.dart
  concordia_nav/test/map/map_viewmodel_test.dart
  concordia_nav/test/map/map_viewmodel_test.mocks.dart
Labels: backend

#211 Feature/transport method directions
  concordia_nav/assets/icons/shuttle_bus.png
  concordia_nav/assets/icons/shuttle_bus_station.png
  concordia_nav/assets/maps/outdoor/shuttle_bus_routes/loy_to_sgw.json
  concordia_nav/assets/maps/outdoor/shuttle_bus_routes/sgw_to_loy.json
  concordia_nav/assets/maps/outdoor/shuttle_bus_schedules/friday.json
  concordia_nav/assets/maps/outdoor/shuttle_bus_schedules/monday_thursday.json
  concordia_nav/lib/data/repositories/outdoor_directions_repository.dart
  concordia_nav/lib/data/services/map_service.dart
  concordia_nav/lib/data/services/outdoor_directions_service.dart
  concordia_nav/lib/ui/campus_map/campus_map_view.dart
  concordia_nav/lib/ui/outdoor_location/outdoor_location_map_view.dart
  concordia_nav/lib/utils/map_viewmodel.dart
  concordia_nav/lib/widgets/compact_location_search_widget.dart
  concordia_nav/maestro/1_3_Outdoor_Direction_Option.yaml
  concordia_nav/pubspec.lock
  concordia_nav/pubspec.yaml
  concordia_nav/test/building/building_info_drawer_test.dart
  concordia_nav/test/directions/outdoor_directions_repository_test.dart
  concordia_nav/test/directions/outdoor_directions_test.dart
  concordia_nav/test/directions/outdoor_directions_test.mocks.dart
  concordia_nav/test/homepage_test.dart
  concordia_nav/test/map/campus_test.dart
  concordia_nav/test/map/campus_test.mocks.dart
  concordia_nav/test/map/map_service_test.dart
  concordia_nav/test/map/map_viewmodel_test.dart
  concordia_nav/test/map/map_viewmodel_test.mocks.dart
  concordia_nav/test/splash_screen_test.dart
Labels: backend, feature

#217 Add indoor routing based on steepest-ascent hill climbing
  concordia_nav/lib/data/domain-model/concordia_building.dart
  concordia_nav/lib/data/domain-model/concordia_floor.dart
  concordia_nav/lib/data/domain-model/concordia_floor_point.dart
  concordia_nav/lib/data/domain-model/concordia_room.dart
  concordia_nav/lib/data/domain-model/connection.dart
  concordia_nav/lib/data/domain-model/floor_routable_point.dart
  concordia_nav/lib/data/domain-model/indoor_route.dart
  concordia_nav/lib/data/repositories/indoor_feature_repository.dart
  concordia_nav/lib/data/services/indoor_routing_service.dart
  concordia_nav/pubspec.lock
  concordia_nav/pubspec.yaml
  concordia_nav/test/indoor_map/indoor_route_test.dart
  concordia_nav/test/indoor_map/indoor_routing_service_test.dart
Labels: backend
